cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAZNLZY4XGXU4H5YSF
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error